@base_url = http://localhost:8082/v1/2024

# Register
### Register a new user
POST {{base_url}}/user/register
Content-Type: application/json

{
    "verify_key": "quang0706rr1@gmail.com",
    "verify_type": 1,
    "verify_purpose": "TEST_USER"
}


### login user
POST {{base_url}}/user/login
Content-Type: application/json

{
    "email": "quang0706r@gmail.com",
    "password": "12345678"
}

###verify otp user 
POST {{base_url}}/user/verifyOTP
Content-Type: application/json

{
    "verify_code": "123456",
    "verify_key": "quang0706r@gmail.com"
}