// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PreEventLikeUser struct {
	EventID pgtype.UUID
	UserID  pgtype.UUID
	LikedAt pgtype.Timestamp
}

type PreGoContactMessage struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     pgtype.Text
	Message   string
	Status    int16
	CreatedAt pgtype.Timestamptz
}

type PreGoEvent struct {
	ID               pgtype.UUID
	EventName        string
	EventDescription pgtype.Text
	EventImageUrl    pgtype.Text
	EventActive      pgtype.Bool
	EventStart       pgtype.Timestamp
	EventEnd         pgtype.Timestamp
	UserID           pgtype.UUID
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type PreGoMenuFunction struct {
	ID          string
	Name        string
	Description pgtype.Text
	Url         pgtype.Text
	Active      pgtype.Bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PreGoSubMenuFunction struct {
	ID          string
	Name        string
	Description pgtype.Text
	Image       pgtype.Text
	Url         pgtype.Text
	Menufuncid  string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
